# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwayland-dev libxkbcommon-dev xorg-dev libgtk-3-dev
        version: 1.0

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: true # Pull down submodules then check if we have a valid chache

    - name: Submodule Hash
      id: submodule-hash
      uses: Andthehand/submodule-version-hash-action@main
      with: 
        path: '.'

    - name : Cache Submodules
      id: cache-submodule
      uses: actions/cache@v4
      with:
        path: |
          vendor
          build/vendor
        key: ${{ matrix.os }}-submodules-${{ steps.submodule-hash.outputs.sha256 }}

    - name: Update git submodules
      if: steps.cache-submodule.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build 
        -DTRACY_ENABLE=OFF
    
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --parallel

    # - name: Run GTests (Linux)
    #   if: matrix.os == 'ubuntu-latest'
    #   run: ${{ github.workspace }}/build/tests/RealEngineTests

    - name: Run GTests (Windows)
      if: matrix.os == 'windows-latest'
      run: ${{ github.workspace }}\build\tests\Debug\RealEngineTests.exe
